# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='hood_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='hood_description',
            field=models.TextField(choices=[('NairobiWest', 'NairobiWest'), ('South C', 'South C'), ('South B', 'South B'), ('Westlands', 'Westlands')], max_length=100),
        ),
    ]
