# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='hood_location',
            field=models.CharField(choices=[('NairobiWest', 'Nairobi West'), ('SouthC', 'South C'), ('SouthB', 'South B'), ('Westlands', 'Westlands')], max_length=50),
        ),
    ]
