# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-17 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_photo',
            field=models.ImageField(default='', upload_to='pictures/'),
        ),
    ]
