# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181019_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_bio',
            field=models.TextField(default='Awesome bio will appear here', max_length=200),
        ),
    ]
