# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181017_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='user_profile',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='hood_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_id',
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='hood_address',
            field=django_google_maps.fields.AddressField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='hood_location',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100),
        ),
    ]
